/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.BindException;
import java.util.Enumeration;
import java.util.Hashtable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JRadioButton;
import pong.Pong;

/**
 *
 * @author Maxwell
 */
public class HostGame extends javax.swing.JPanel {
    private int numPlayers=0;
    private Class whichGame=null;
    private Client client;
    private Hashtable<String,JRadioButton> radioButtons;
    public HostGame(Client client) {
        initComponents();
        radioButtons=new Hashtable<String,JRadioButton>();
        jLabel3.setVisible(false);
        this.client=client;
        jTextField1.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) { 
                if (jTextField1.getText().length() >= 5 ) // limit textfield to 5 characters
                    e.consume(); 
            }  
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Host Game");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        jScrollPane1.setBorder(null);

        jList1.setBackground(new java.awt.Color(153, 153, 153));
        jList1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Pong" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setFocusable(false);
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, 90));

        jLabel2.setText("Games");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 40, -1));

        jLabel3.setText("Players");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));

        jButton1.setText("Start Server");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, -1));

        jLabel4.setText("Port");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 20, -1));

        jTextField1.setText("7777");
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 70, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Back");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(numPlayers==0||whichGame==null)
            return;
        int port;
        try{
            if(jTextField1.getText().equals(""))
                return;
            port=Integer.parseInt(jTextField1.getText());
        }
        catch(NumberFormatException ex){
            return;
        }
        try {
            client.hostServer("127.0.0.1", port,numPlayers,whichGame);
        }
         catch(BindException ex){
            return;
        }
          catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        client.frame.remove(client.components.get(HostGame.class));
        client.components.put(Connections.class, new Connections(client,whichGame,numPlayers));
        client.frame.add(client.components.get(Connections.class));
        client.frame.pack();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        String selectedGame=jList1.getSelectedValue();
        jLabel3.setVisible(true);
        for(Enumeration buttons=buttonGroup1.getElements();buttons.hasMoreElements();){
            this.remove((Component)buttons.nextElement());
        }
        switch(selectedGame){
            case "Pong":{
                for(int i=0;i<1;i++){
                    JRadioButton temp = new JRadioButton();
                    temp.setBackground(new Color(153,153,153));
                    temp.setFocusable(false);
                    temp.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            RadioButtonActionPerformed(evt);
                        }
                    });
                    switch(i){
                        case 0: {
                            temp.setText("2 Players");
                            temp.setActionCommand("2");
                        }
                    }
                    buttonGroup1.add(temp);
                    add(temp, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150+(i*15), -1, -1));
                }
                whichGame=Pong.class;
            }
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        client.components.put(Menu.class, new Menu(client));
        client.frame.remove(client.components.get(HostGame.class));
        client.components.remove(HostGame.class);
        client.frame.add(client.components.get(Menu.class));
        client.frame.pack();
    }//GEN-LAST:event_jLabel5MouseClicked
    public void RadioButtonActionPerformed(ActionEvent evt){
        numPlayers=Integer.parseInt(evt.getActionCommand());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
